DROP ALL OBJECTS;

CREATE TABLE CUSTOMER (
  ID           VARCHAR(50),
  EMAIL        VARCHAR(120) NOT NULL,
  FIRSTNAME    VARCHAR(50)  NOT NULL,
  LASTNAME     VARCHAR(50),
  MOBILENUMBER VARCHAR(13)  NOT NULL,
  CREATEDATE   TIMESTAMP    NOT NULL,
  UPDATEDATE   TIMESTAMP    NOT NULL,
  CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID),
  CONSTRAINT CUSTOMER_UK UNIQUE (EMAIL)
);

CREATE TABLE ITEM_CATEGORY (
  ID                  VARCHAR(50),
  NAME                VARCHAR(20)   NOT NULL,
  ITEM_CATEGORY_PRICE NUMERIC(8, 2) NOT NULL,
  CREATEDATE          TIMESTAMP     NOT NULL,
  UPDATEDATE          TIMESTAMP     NOT NULL,
  CONSTRAINT ITEM_CATEGORY_PK PRIMARY KEY (ID)
);

CREATE TABLE ITEM (
  ID               VARCHAR(50),
  NAME             VARCHAR(50)  NOT NULL,
  DESCRIPTION      VARCHAR(100) NOT NULL,
  ITEM_CATEGORY_ID VARCHAR(50)  NOT NULL,
  CREATEDATE       TIMESTAMP    NOT NULL,
  UPDATEDATE       TIMESTAMP    NOT NULL,
  CONSTRAINT ITEM_CATEGORY_FK FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES ITEM_CATEGORY (ID),
  CONSTRAINT ITEM_PK PRIMARY KEY (ID)
);

CREATE TABLE ITEM_INVENTORY (
  ID                  VARCHAR(50),
  ITEM_ID             VARCHAR(50) NOT NULL,
  REGISTRATION_NUMBER VARCHAR(50),
  PRICE               NUMERIC(8, 2),
  CREATEDATE          TIMESTAMP   NOT NULL,
  UPDATEDATE          TIMESTAMP   NOT NULL,
  CONSTRAINT ITEM_INVENTORY_PK PRIMARY KEY (ID),
  CONSTRAINT ITEM_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE TABLE BOOKING (
  ID                VARCHAR(50),
  CUSTOMER_ID       VARCHAR(50) NOT NULL,
  ITEM_INVENTORY_ID VARCHAR(50) NOT NULL,
  FROM_DATE         DATE,
  TO_DATE           DATE,
  CREATEDATE        TIMESTAMP   NOT NULL,
  UPDATEDATE        TIMESTAMP   NOT NULL,
  CONSTRAINT BOOKING_PK PRIMARY KEY (ID),
  CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
  CONSTRAINT ITEM_INVENTORY_FK FOREIGN KEY (ITEM_INVENTORY_ID) REFERENCES ITEM_INVENTORY (ID)
);

COMMIT;


